@ItineraryOperations_HostAddress = http://localhost:5212

POST {{ItineraryOperations_HostAddress}}/Calculations/taskOrder/5
Accept: application/json

###

POST {{ItineraryOperations_HostAddress}}/Calculations/operation/21
Accept: application/json

###

GET {{ItineraryOperations_HostAddress}}/Calculations/operation/1
Accept: application/json

###

Delete {{ItineraryOperations_HostAddress}}/Calculations/operation/1
Accept: application/json

###

GET {{ItineraryOperations_HostAddress}}/api/OperationsOfItinerary
Accept: application/json

###
GET {{ItineraryOperations_HostAddress}}/api/Executors
Accept: application/json
Content-Type: application/json

###
GET {{ItineraryOperations_HostAddress}}/api/Products
Accept: application/json
Content-Type: application/json

{
  "DivisionID": 115,
  "ExecutorID": 2,
  "Operations": []
}
