// <auto-generated />
using System;
using ItineraryOperations.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ItineraryOperations.Migrations
{
    [DbContext(typeof(PostgresContext))]
    [Migration("20251215113215_InitialCreateV2")]
    partial class InitialCreateV2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ItineraryOperations.Models.Divisions", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("Divisions");
                });

            modelBuilder.Entity("ItineraryOperations.Models.Equipment", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int>("Name")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.ToTable("Equipment");
                });

            modelBuilder.Entity("ItineraryOperations.Models.Executors", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int>("DivisionID")
                        .HasColumnType("integer");

                    b.Property<string[]>("Members")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<bool>("isBrigade")
                        .HasColumnType("boolean");

                    b.HasKey("ID");

                    b.HasIndex("DivisionID");

                    b.ToTable("Executors");
                });

            modelBuilder.Entity("ItineraryOperations.Models.Itinerary", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("AUDCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("KitIncreasingKit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NameProduct")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NumberPositions")
                        .HasColumnType("integer");

                    b.Property<int>("PositionPlanID")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.HasIndex("AUDCode");

                    b.HasIndex("PositionPlanID");

                    b.ToTable("Itineraries");
                });

            modelBuilder.Entity("ItineraryOperations.Models.MainSubject", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("AUDCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("MainSubject");
                });

            modelBuilder.Entity("ItineraryOperations.Models.OperationCategories", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int>("DivisionID")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Payment")
                        .HasColumnType("numeric");

                    b.HasKey("ID");

                    b.HasIndex("DivisionID");

                    b.ToTable("OperationCategories");
                });

            modelBuilder.Entity("ItineraryOperations.Models.OperationsOfItinerary", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int>("CategoryID")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("DateExecution")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DateIssue")
                        .HasColumnType("date");

                    b.Property<int>("DivisionID")
                        .HasColumnType("integer");

                    b.Property<int>("EquipmentID")
                        .HasColumnType("integer");

                    b.Property<int>("ExecutorID")
                        .HasColumnType("integer");

                    b.Property<int>("ItineraryID")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("NormTime")
                        .HasColumnType("double precision");

                    b.Property<int>("NumberPositions")
                        .HasColumnType("integer");

                    b.Property<float>("PaymentCoefficient")
                        .HasColumnType("decimal(6,4)");

                    b.Property<float>("Reward")
                        .HasColumnType("decimal(7,3)");

                    b.Property<float>("RewardAmount")
                        .HasColumnType("decimal(10,3)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int?>("TaskOrdersID")
                        .HasColumnType("integer");

                    b.Property<float>("TotalWithSurcharge")
                        .HasColumnType("decimal(10,3)");

                    b.Property<int>("TypeOperationID")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.HasIndex("CategoryID");

                    b.HasIndex("DivisionID");

                    b.HasIndex("EquipmentID");

                    b.HasIndex("ExecutorID");

                    b.HasIndex("ItineraryID");

                    b.HasIndex("TaskOrdersID");

                    b.HasIndex("TypeOperationID");

                    b.ToTable("OperationsOfItinerary");
                });

            modelBuilder.Entity("ItineraryOperations.Models.PlanPosition", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int>("ProductID")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.HasIndex("ProductID");

                    b.ToTable("PlanPositions");
                });

            modelBuilder.Entity("ItineraryOperations.Models.Products", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("AUDCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.HasIndex("AUDCode");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("ItineraryOperations.Models.TaskOrders", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int>("DivisionID")
                        .HasColumnType("integer");

                    b.Property<int>("ExecutorID")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.HasIndex("DivisionID");

                    b.HasIndex("ExecutorID");

                    b.ToTable("TaskOrders");
                });

            modelBuilder.Entity("ItineraryOperations.Models.TypesOperations", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("TypesOperations");
                });

            modelBuilder.Entity("ItineraryOperations.Models.Executors", b =>
                {
                    b.HasOne("ItineraryOperations.Models.Divisions", "Divisions")
                        .WithMany()
                        .HasForeignKey("DivisionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Divisions");
                });

            modelBuilder.Entity("ItineraryOperations.Models.Itinerary", b =>
                {
                    b.HasOne("ItineraryOperations.Models.MainSubject", "MainSubject")
                        .WithMany()
                        .HasForeignKey("AUDCode")
                        .HasPrincipalKey("AUDCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ItineraryOperations.Models.PlanPosition", "PlanPosition")
                        .WithMany()
                        .HasForeignKey("PositionPlanID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MainSubject");

                    b.Navigation("PlanPosition");
                });

            modelBuilder.Entity("ItineraryOperations.Models.OperationCategories", b =>
                {
                    b.HasOne("ItineraryOperations.Models.Divisions", "Division")
                        .WithMany()
                        .HasForeignKey("DivisionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Division");
                });

            modelBuilder.Entity("ItineraryOperations.Models.OperationsOfItinerary", b =>
                {
                    b.HasOne("ItineraryOperations.Models.OperationCategories", "OperationCategory")
                        .WithMany()
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ItineraryOperations.Models.Divisions", "Division")
                        .WithMany()
                        .HasForeignKey("DivisionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ItineraryOperations.Models.Equipment", "Equipments")
                        .WithMany()
                        .HasForeignKey("EquipmentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ItineraryOperations.Models.Executors", "Executor")
                        .WithMany()
                        .HasForeignKey("ExecutorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ItineraryOperations.Models.Itinerary", "Itinerary")
                        .WithMany("Operations")
                        .HasForeignKey("ItineraryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ItineraryOperations.Models.TaskOrders", null)
                        .WithMany("Operations")
                        .HasForeignKey("TaskOrdersID");

                    b.HasOne("ItineraryOperations.Models.TypesOperations", "TypeOperation")
                        .WithMany()
                        .HasForeignKey("TypeOperationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Division");

                    b.Navigation("Equipments");

                    b.Navigation("Executor");

                    b.Navigation("Itinerary");

                    b.Navigation("OperationCategory");

                    b.Navigation("TypeOperation");
                });

            modelBuilder.Entity("ItineraryOperations.Models.PlanPosition", b =>
                {
                    b.HasOne("ItineraryOperations.Models.Products", "Product")
                        .WithMany()
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ItineraryOperations.Models.Products", b =>
                {
                    b.HasOne("ItineraryOperations.Models.MainSubject", "MainSubject")
                        .WithMany()
                        .HasForeignKey("AUDCode")
                        .HasPrincipalKey("AUDCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MainSubject");
                });

            modelBuilder.Entity("ItineraryOperations.Models.TaskOrders", b =>
                {
                    b.HasOne("ItineraryOperations.Models.Divisions", "Division")
                        .WithMany()
                        .HasForeignKey("DivisionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ItineraryOperations.Models.Executors", "Executor")
                        .WithMany()
                        .HasForeignKey("ExecutorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Division");

                    b.Navigation("Executor");
                });

            modelBuilder.Entity("ItineraryOperations.Models.Itinerary", b =>
                {
                    b.Navigation("Operations");
                });

            modelBuilder.Entity("ItineraryOperations.Models.TaskOrders", b =>
                {
                    b.Navigation("Operations");
                });
#pragma warning restore 612, 618
        }
    }
}
